@startuml

' Define the skin parameters for better visualization
skinparam rectangle {
  StrokeColor Black
  BorderColor Black
}

' Entities
entity User {
  + User UID: String
  + Email: String
  + Password: String
}

entity QuizCollection {
  + QuizID: String
  + QuizQuestions: List
  + QuizOptions: List
  + QuizAnswers: List
}

entity QuizCollectionResults {
  + quizID: String
  + Score: Number
  + id: PK
  + timestamp: Date
}

entity JournalCollection {
  + DocumentID: String
  + Entry: String
  + Time: Date
}

entity MoodsCollection {
  + DocumentID: String
  + Mood: String
  + Time: Date
}

' Firebase database mockup
rectangle Firebase {
  ' Placeholder to represent Firebase
}

' Data flows
User --> Firebase : Checks Email and Password
Firebase --> User : Retrieves User UID (if email and password match)
User --> Firebase : Stores User UID as Variable
Firebase --> QuizCollection : Retrieves Questions
QuizCollection --> User : Sends Questions
User <-- QuizCollectionResults : Retrieves Results
Firebase --> JournalCollection : Stores Entries
JournalCollection --> User : Retrieves Entries
Firebase <-- MoodsCollection : Stores Moods
MoodsCollection --> User : Retrieves Moods

' Showing data storage in Firebase
Firebase <-- QuizCollectionResults : Stores Quiz Results
Firebase <-- JournalCollection : Stores Journal Entries

@enduml
