@startuml PasswordReset
set namespaceSeparator ::

class "big_feelings::Pages::Auth::Reset%20Password::reset_desktop.dart::PasswordResetDesktop" {
  +_PasswordResetDesktopState createState()
}
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "big_feelings::Pages::Auth::Reset%20Password::reset_desktop.dart::PasswordResetDesktop"

class "big_feelings::Pages::Auth::Reset%20Password::reset_desktop.dart::_PasswordResetDesktopState" {
  +TextEditingController emailController
  -bool? _emailSent
  +void initState()
  -void _clearError()
  -void _sendPasswordResetEmail()
  +Widget build()
}
"big_feelings::Pages::Auth::Reset%20Password::reset_desktop.dart::_PasswordResetDesktopState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "big_feelings::Pages::Auth::Reset%20Password::reset_desktop.dart::_PasswordResetDesktopState"

class "big_feelings::Pages::Auth::Reset%20Password::reset_mobile.dart::PasswordResetMobile" {
  +_PasswordResetMobileState createState()
}
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "big_feelings::Pages::Auth::Reset%20Password::reset_mobile.dart::PasswordResetMobile"

class "big_feelings::Pages::Auth::Reset%20Password::reset_mobile.dart::_PasswordResetMobileState" {
  +TextEditingController emailController
  -bool? _emailSent
  +void initState()
  -void _clearError()
  -void _sendPasswordResetEmail()
  +Widget build()
}
"big_feelings::Pages::Auth::Reset%20Password::reset_mobile.dart::_PasswordResetMobileState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "big_feelings::Pages::Auth::Reset%20Password::reset_mobile.dart::_PasswordResetMobileState"

@enduml
