// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5VFEcyMYQcPn3pmP1sSMiA0b_XivRi0',
    appId: '1:570688112323:web:0f541eef508257f401c476',
    messagingSenderId: '570688112323',
    projectId: 'big-feelings-project',
    authDomain: 'big-feelings-project.firebaseapp.com',
    storageBucket: 'big-feelings-project.appspot.com',
    measurementId: 'G-JFQ05XFF44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBhMJQGH_8Giv4mZn1qxZO5Zpwe9djB0',
    appId: '1:570688112323:android:ff0771cbe13acdd401c476',
    messagingSenderId: '570688112323',
    projectId: 'big-feelings-project',
    storageBucket: 'big-feelings-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLFYY8O_t7YBN9g4IxTX2m_Vk5ORcaBiM',
    appId: '1:570688112323:ios:ac0875e58b137fd301c476',
    messagingSenderId: '570688112323',
    projectId: 'big-feelings-project',
    storageBucket: 'big-feelings-project.appspot.com',
    iosBundleId: 'com.example.bigFeelings',
  );
}
