name: big_feelings
description: "A web application to teach children about their emotions, how to manage them and validate them."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_analytics: ^10.8.4
  provider: ^6.1.1
  logger: ^2.0.2+1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.5
  intl: ^0.19.0
  table_calendar: ^3.1.0
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - web/icons/bigfeelings_logo.png
    - assets/images/
    - assets/icons/
    - assets/images/images_mood/
    - fonts/
    - assets/animation/
   
  fonts:
    - family: SingleDay
      fonts:
        - asset: fonts/SingleDay-Regular.ttf
    